---
version: '3.4'
services:
  # gitlab-clab-launcher:
  #     build:
  #       context: clab/
  #       dockerfile: Dockerfile
  #     image: "gitlab-clab-launcher"
  #     networks:
  #       net1:
  #         ipv4_address: 172.254.0.254
  #     privileged: true
  #     pid: host
  #     working_dir: ${PWD}/clab/
  #     volumes:
  #         - ${PWD}/clab/:${PWD}/clab/
  #         - /var/run/docker.sock:/var/run/docker.sock
  #         - /run/netns:/run/netns

  rg-gitlab:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://10.254.254.7:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    networks:
      net1:
        ipv4_address: 172.254.0.253
    ports:
      - '8929:8929'
      - '2224:2224'
    volumes:
      - '${PWD}/gitlab/config:/etc/gitlab'
      - '${PWD}/gitlab/logs:/var/log/gitlab'
      - '${PWD}/gitlab/data:/var/opt/gitlab'



networks:
  net1:
    # naming this to match the containerlab network to put everything in the same network to make life easy
    name: rgclab
    ipam:
      config:
        - subnet: 172.254.0.0/24
          gateway: 172.254.0.1
